name: AUR Import
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_BASENAME: ${{ github.repository_owner }}

jobs:
  publish:
    name: Docker Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./docker-build.sh
      - name: Publish
        run: ./docker-publish.sh "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_BASENAME }}"
